# Strict mode; errexit, nounset & xtrace pipefail
set shell := ["bash", "-euo", "pipefail", "-c"]
set guards

export JUST_COMPLETIONS := env("HOME") + "/.local/share/bash-completion/completions"

export PNPM_HOME := env("HOME") / ".local/share/pnpm"
export UV_INSTALL_DIR := env("HOME") / ".local/bin"


# UTILITY - Recipes
# -----------------------------------------------

[default]
[doc("Shorthand for `just --list`")]
@_:
    just --justfile {{justfile()}} --list

_log COLOUR MSG:
    @echo "{{ BOLD + COLOUR }}[INFO] {{ MSG }}{{ NORMAL }}"

# INSTALL - Recipes
# -----------------------------------------------

[doc("Install Astral `uv` package manager [idempotent]")]
[env("PATH", `[[ ":$PATH:" == *":$UV_INSTALL_DIR:"* ]] && echo "$PATH" || echo "$UV_INSTALL_DIR:$PATH"`)]
[group("INSTALL")]
install-uv: && (_log BLUE "UV IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v uv >/dev/null 2>&1; then
        wget -qO- https://astral.sh/uv/install.sh | bash
    fi

[doc("Install `pnpm` package manager [idempotent]")]
[env("PATH", `[[ ":$PATH:" == *":$PNPM_HOME/bin:"* ]] && echo "$PATH" || echo "$PNPM_HOME/bin:$PATH"`)]
[group("INSTALL")]
install-pnpm: && (_log BLUE "PNPM IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v pnpm >/dev/null 2>&1; then
        wget -qO- https://get.pnpm.io/install.sh | bash -
    fi

[doc("Install `Node.js` LTS globally [idempotent]")]
[env("PATH", `[[ ":$PATH:" == *":$PNPM_HOME/bin:"* ]] && echo "$PATH" || echo "$PNPM_HOME/bin:$PATH"`)]
[group("INSTALL")]
install-pnpm-runtime: install-pnpm && (_log BLUE "NODE IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v node >/dev/null 2>&1; then
        pnpm runtime set node lts -g
    fi
    pnpm list -g node

[doc("Install `podman` container engine [idempotent]")]
[group("INSTALL")]
install-podman: update-packages && (_log BLUE "PODMAN IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v podman >/dev/null 2>&1; then
        sudo xbps-install podman
    fi

[doc("Install `podman-compose` parser [idempotent]")]
[env("PATH", `[[ ":$PATH:" == *":$UV_INSTALL_DIR:"* ]] && echo "$PATH" || echo "$UV_INSTALL_DIR:$PATH"`)]
[group("INSTALL")]
install-podman-compose: install-uv && (_log BLUE "PODMAN-COMPOSE IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v podman-compose >/dev/null 2>&1; then
        uv tool install podman-compose
    fi

[doc("Install `just-lsp` language server for `Just` [idempotent]")]
[group("INSTALL")]
install-justlsp: update-packages && (_log BLUE "JUST-LSP IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v just-lsp >/dev/null 2>&1; then
        sudo xbps-install just-lsp
    fi

[doc("Install `dive` image exploration tool")]
[group("INSTALL")]
install-dive: update-packages && (_log BLUE "DIVE IS INSTALLED")
    #!/usr/bin/env bash
    if ! command -v dive >/dev/null 2>&1; then
        sudo xbps-install dive
    fi

# UPDATE - Recipes
# -----------------------------------------------

[doc("Run `sudo xbps-install -Su`")]
[arg("FLAGS", help="Optional `xbps-install` FLAGS")]
[group("UPDATE")]
update-packages *FLAGS: (_log BLUE "UPDATING PACKAGES")
    sudo xbps-install -Su {{FLAGS}}

[doc("Update `Just` bash completions")]
[group("UPDATE")]
update-just-completions:
    #!/usr/bin/env bash
    mkdir -p "$JUST_COMPLETIONS"
    just --completions bash > "$JUST_COMPLETIONS/just"
