# Strict mode; errexit, nounset & xtrace pipefail
set shell := ["bash", "-euo", "pipefail", "-c"]

# Pre-emptively add `uv` & `pnpm` default install paths to `$PATH`
export PATH := env("HOME") + "/.local/share/pnpm:" + env("HOME") + "/.local/bin:" + env("PATH")

[default]
[doc("Shorthand for `just --list`")]
@_:
  just --justfile {{justfile()}} --list


[doc("Run `sudo xbps-install -Su`")]
[group("XBPS")]
xbps-su:
  sudo xbps-install -Su


[doc("Run `sudo xbps-remove -Oo`")]
[group("XBPS")]
xbps-oo:
  sudo xbps-remove -Oo


[doc("Install Astral `uv` Python package manager [idempotent]")]
[group("DEV")]
install-uv:
  #!/usr/bin/env bash
  set -euo pipefail

  if ! command -v uv >/dev/null 2>&1 && [ ! -f "$HOME/.local/bin/uv" ]; then
    wget -qO- https://astral.sh/uv/install.sh | bash
  else
    echo "Found existing uv package"
  fi


[doc("Install `pnpm` `Node.js` package manager [idempotent]")]
[group("DEV")]
install-pnpm:
  #!/usr/bin/env bash
  set -euo pipefail

  if ! command -v pnpm >/dev/null 2>&1 && [ ! -f "$HOME/.local/share/pnpm/pnpm" ]; then
    wget -qO- https://get.pnpm.io/install.sh | bash -
    echo "RUN: source $HOME/.bashrc"
  else
    echo "Found existing pnpm package"
  fi


[doc("Install the LTS version of `Node.js` [idempotent]")]
[group("DEV")]
pnpm-env: install-pnpm
	pnpm env use --global lts && pnpm env list


[doc("Update `pnpm` `Node.js` package manager")]
[group("DEV")]
pnpm-update: install-pnpm
	pnpm self-update


[doc("Install `podman` container engine [idempotent]")]
[group("DEV")]
install-podman: xbps-su
  #!/usr/bin/env bash
  set -euo pipefail

  if ! command -v podman >/dev/null 2>&1 && [ ! -f "/usr/sbin/podman" ]; then
    sudo xbps-install podman
  else
    echo "Found existing podman package"
  fi


[doc("Install `just-lsp` language server for `Just` [idempotent]")]
[group("DEV")]
install-justlsp: xbps-su
  #!/usr/bin/env bash
  set -euo pipefail

  if ! command -v just-lsp >/dev/null 2>&1 && [ ! -f "/usr/sbin/just-lsp" ]; then
    sudo xbps-install just-lsp
  else
    echo "Found existing just-lsp package"
  fi


[doc("Install `podman-compose` parser [idempotent]")]
[group("DEV")]
install-podman-compose: install-uv
  #!/usr/bin/env bash
  set -euo pipefail

  if ! command -v podman-compose >/dev/null 2>&1 && [ ! -f "$HOME/.local/bin/podman-compose" ]; then
    uv tool install podman-compose
  else
    echo "Found existing podman-compose package"
  fi


[doc("Install `dive` `Docker` image exploration tool")]
[group("DEV")]
install-dive: xbps-su
  #!/usr/bin/env bash
  if ! command -v dive >/dev/null 2>&1 && [ ! -f "/usr/sbin/dive" ]; then
    sudo xbps-install dive
  else
    echo "Found existing dive package"
  fi