# /etc/wsl.conf

[boot]
# Command to start `runit` stages 1 (WAIT) -> 2 (BACKGROUND) 
command = "/etc/runit/1 && (/etc/runit/2 &) || echo '/etc/runit/1 failed' > /var/log/runit-error.log"
systemd = false
# Prevent `systemd` units generation (when systemd = true)
protectBinfmt = false

[automount]
# Automatically mount Windows drives
enabled = true
# Automatically generate `/etc/ld.so.conf.d/ld.wsl.conf`
ldconfig = true
# Mount entries from /etc/fstab
mountFsTab = true
# Default mount root for Windows drives
root = /mnt/
# Mounting options (metadata allows for Linux permissions on Windows files)
# https://learn.microsoft.com/en-us/windows/wsl/file-permissions
options = "metadata,rw,uid=1000,gid=1000,umask=022,dmask=000,fmask=000,case=off"

[network]
# Automatically generate configuration files
generateHosts = true
# Automatically generate `/etc/resolv.conf` DNS list
generateResolvConf = true

[gpu]
# GPU acceleration settings
enabled = true
# Append GPU driver paths `/etc/ld.so.conf.d/`
appendLibPath = false

[time]
# Sync time with Windows host
useWindowsTimezone = true

[interop]
# Integration with Windows binaries
enabled = true
# Append Windows $PATH to Linux $PATH
appendWindowsPath = true

[user]
# User created by bootstrap script
default = "void"